#!/usr/bin/env python

from subprocess import Popen, PIPE, STDOUT
import os
import shutil
import sys

RELEASE = '65ab0c3'
CDIR = os.path.abspath('.')

def bin_exec(command, cwd=os.environ['PWD']):
  p = Popen(command, cwd=cwd)
  p.wait()
  return p.returncode

def install_pants():
  CLONE_DIR = os.path.expanduser(os.path.join('~', '.temp-pants'))
  if os.path.exists(CLONE_DIR):
    shutil.rmtree(CLONE_DIR)
  bin_exec(['git', 'clone', 'https://github.com/pantsbuild/pants.git', CLONE_DIR])
  bin_exec(['git', 'checkout', RELEASE], cwd=CLONE_DIR)
  bin_exec([os.path.join(CLONE_DIR, 'pants')], cwd=CLONE_DIR)
  shutil.copyfile(os.path.join(CLONE_DIR, 'pants.pex'), 'pants.pex')
  shutil.rmtree(CLONE_DIR)
  bin_exec(['chmod', '+x', 'pants.pex'])


if __name__ == '__main__':
  args = sys.argv[1:]
  if len(args) >= 2 and args[0] == '-commit':
    RELEASE = args[1]
    args = args[2:]
    print 'Using pants repo commit', RELEASE
  if not os.path.exists('pants.pex'):
    install_pants()
  bin_exec([os.path.join(CDIR, 'pants.pex'),] + sys.argv[1:])



